version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.1.0
  aws-ecr: circleci/aws-ecr@9.3.4
  aws-ecs: circleci/aws-ecs@4.1.0
  aws-s3: circleci/aws-s3@4.0.0
  browser-tools: circleci/browser-tools@1.4.8
  jira: circleci/jira@2.1.0
  slack: circleci/slack@4.14.0

jobs:
  test:
    resource_class: large
    docker:
      - image: cimg/node:20.13.1-browsers
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN

    working_directory: ~/donate

    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

      - checkout

      - restore_cache:
          keys:
            - dependencies-with-chrome-{{ checksum "package-lock.json" }}

      - run: npm install --quiet

      - save_cache:
          paths:
            - node_modules
            - /home/circleci/.cache/Cypress
            - /home/circleci/.cache/puppeteer
          key: dependencies-with-chrome-{{ checksum "package-lock.json" }}

      - run: npm run ci

      - store_artifacts:
          path: cypress/screenshots

  build-ecr:
    resource_class: large
    machine:
      enabled: true
      docker_layer_caching: true
    parameters:
      env:
        type: string
    steps:
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          # cache-from format is e.g. 123.dkr.ecr.eu-west-1.amazonaws.com/thebiggive-donate:staging
          extra_build_args: '--build-arg BUILD_ENV=<< parameters.env >> --build-arg FONTAWESOME_NPM_AUTH_TOKEN=${FONTAWESOME_NPM_AUTH_TOKEN} --cache-from "${AWS_ECR_ACCOUNT_URL}/${AWS_ECR_REPO_NAME}:<< parameters.env >>"'
          repo: '${AWS_ECR_REPO_NAME}'
          region: '${AWS_REGION}'
          tag: '<< parameters.env >>,<< parameters.env >>-${CIRCLE_SHA1}'

  copy-ecr-static-to-s3:
    parameters:
      env:
        type: string
    docker:
      - image: "${AWS_ECR_ACCOUNT_URL}/${AWS_ECR_REPO_NAME}:<< parameters.env >>-${CIRCLE_SHA1}"
    steps:
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY

      - aws-s3/sync: # Sync dist/browser to S3 with 1 year lifetime
          from: /usr/src/app/dist/browser
          to: 's3://tbg-<< parameters.env >>-donate-static/d'
          arguments: '--acl public-read --cache-control "max-age=31536000"'

      - aws-s3/sync: # Sync dist/browser/assets to S3 with 1 day lifetime
          from: /usr/src/app/dist/browser/assets
          to: 's3://tbg-<< parameters.env >>-donate-static/assets'
          arguments: '--acl public-read --cache-control "max-age=86400"'

  notify:
    parameters:
      env:
        type: string
    resource_class: large
    docker:
      - image: cimg/node:20.13.1-browsers
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
    steps:
      - checkout
      - jira/notify:
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
          job_type: deployment
          environment: << parameters.env >>
          environment_type: << parameters.env >>
      - run:
          name: Notify Slack
          command: |
            curl -H "Content-type: application/json" --data '{"channel":"deployments","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"$CIRCLE_BRANCH Donate frontend deployed!* All visitors should see the updated app version within 30 minutes"}}]}' -H "Authorization: Bearer $SLACK_ACCESS_TOKEN" -X POST https://slack.com/api/chat.postMessage
workflows:
  commit:
    jobs:
      - test:
          context:
            - docker-hub-creds
            - jira
          post-steps:
            - jira/notify:
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>
                job_type: build
                environment_type: development
      - notify:
          context:
            - slack
            - jira
          # temporarily notifying slack on every commit until we can see the notification working.
          requires: ["test"]
          env: testing

  deploy-regression:
    jobs:
      - build-ecr:
          filters:
            branches:
              only:
                - develop
          env: regression
          name: "Build Regression ECR image"
          context:
            - docker-hub-creds
            - ecs-deploys
          post-steps:
            - slack/notify:
                channel: deployments, regression-alarms
                event: fail
                template: basic_fail_1
                mentions: <@here>
      - copy-ecr-static-to-s3:
          env: regression
          name: "Copy Regression ECR static to S3"
          requires: ["Build Regression ECR image"]
          context:
            - ecs-deploys
            - slack
          post-steps:
            - slack/notify:
                channel: deployments, regression-alarms
                event: fail
                template: basic_fail_1
                mentions: <@here>
      - aws-ecs/deploy_service_update:
          name: "Deploy Regression ECS with new image"
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          context:
            - ecs-deploys
            - slack
          requires: ["Copy Regression ECR static to S3"]
          region: AWS_REGION
          family: 'tbg-regression-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX}'
          cluster: 'tbg-regression-${AWS_REGION}'
          container_image_name_updates: 'container=donate,tag=regression-${CIRCLE_SHA1}'
          post-steps:
            - slack/notify:
                channel: deployments, regression-alarms
                event: fail
                template: basic_fail_1
                mentions: <@here>

  deploy-staging:
    jobs:
      - build-ecr:
          filters:
            branches:
              only:
                - develop
          env: staging
          name: "Build Staging ECR image"
          context:
            - docker-hub-creds
            - ecs-deploys
            - slack
          post-steps:
            - slack/notify:
                channel: deployments, staging-alarms
                event: fail
                template: basic_fail_1
                mentions: <@here>
      - copy-ecr-static-to-s3:
          env: staging
          name: "Copy Staging ECR static to S3"
          requires: ["Build Staging ECR image"]
          context:
            - ecs-deploys
            - slack
          post-steps:
            - slack/notify:
                channel: deployments, staging-alarms
                event: fail
                template: basic_fail_1
                mentions: <@here>
      - aws-ecs/deploy_service_update:
          name: "Deploy Staging ECS with new image"
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          context:
            - ecs-deploys
            - jira
            - slack
          requires: ["Copy Staging ECR static to S3"]
          region: AWS_REGION
          family: 'tbg-staging-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX}'
          cluster: 'tbg-staging-${AWS_REGION}'
          container_image_name_updates: 'container=donate,tag=staging-${CIRCLE_SHA1}'
          post-steps:
            - slack/notify:
                channel: deployments, staging-alarms,
                event: fail
                template: basic_fail_1
                mentions: <@here>
      - notify:
          requires: ["Deploy Staging ECS with new image"]
          env: staging
          context:
            - slack
            - jira

  deploy-production:
    jobs:
      - build-ecr:
          filters:
            branches:
              only:
                - main
          env: production
          name: "Build Production ECR image"
          context:
            - docker-hub-creds
            - ecs-deploys
            - slack
          post-steps:
            - slack/notify:
                channel: deployments, production-alarms
                event: fail
                template: basic_fail_1
                mentions: <@here>
      - copy-ecr-static-to-s3:
          env: production
          name: "Copy Production ECR static to S3"
          requires: ["Build Production ECR image"]
          context:
            - ecs-deploys
            - slack
          post-steps:
            - slack/notify:
                channel: deployments, production-alarms
                event: fail
                template: basic_fail_1
                mentions: <@here>
      - aws-ecs/deploy_service_update:
          name: "Deploy Production ECS with new image"
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          context:
            - ecs-deploys
            - jira
            - slack
          requires: ["Copy Production ECR static to S3"]
          region: AWS_REGION
          family: 'tbg-production-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX}'
          cluster: 'tbg-production-${AWS_REGION}'
          container_image_name_updates: "container=donate,tag=production-${CIRCLE_SHA1}"
          post-steps:
            - slack/notify:
                event: fail
                channel: deployments, production-alarms
                template: basic_fail_1
      - notify:
          requires: ["Deploy Production ECS with new image"]
          env: staging
          context:
            - slack
            - jira
